import Navbar from "@/components/Navbar";
import "./globals.css";
export const metadata = {
  title: "Auth Project",
  description: "Generated by Mayank Kushwaha",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <Navbar />

        {children}
      </body>
    </html>
  );
}
