import Navbar from "@/components/Navbar";
import StoreProvider from "./StoreProvider";
import "./globals.css";
export const metadata = {
  title: "Auth Project",
  description: "Generated by Mayank Kushwaha",
};

export default function RootLayout({ children }) {
  // console.log(children);
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <Navbar />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
